=== orpiske/ssps/src/org/ssps/frontend/archive/dbm/dbm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.orpiske.net/ssps/dbm" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.orpiske.net/ssps/dbm">

    <element name="dbm" type="tns:Dbm"></element>
    
    <complexType name="Dbm">
    	<sequence>
    		<element name="project" type="tns:Project"></element>
    		<element name="build" type="tns:Build"></element>
    		<element name="repository" type="tns:Repository"></element>
    	</sequence>
    </complexType>

    <complexType name="Build">
    	<sequence>
    		<element name="sourceDirectory" type="string"></element>
            <element name="outputDirectory" type="string"></element>
            <element name="artifactPath" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Project">
    	<sequence>
            <element name="group" type="string"></element>
            <element name="name" type="string"></element>
    		<element name="version" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Author">
    	<sequence>
    		<element name="id" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Repository">
    	<sequence>
    		<element name="username" type="string"></element>
            <element name="password" type="string"></element>
            <element name="url" type="string"></element>
        </sequence>
    </complexType>
</schema>

=== orpiske/ssps/src/org/ssps/frontend/archive/dbm/dbm.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbm xmlns="http://www.orpiske.net/ssps/dbm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orpiske.net/ssps/dbm dbm.xsd ">
  <project>
    <name>sample</name>
    <version>1.0.0</version>
  </project>
  <build>
    <sourceDirectory>${basedir}/src/dbm</sourceDirectory>
    <outputDirectory>${basedir}/target/installroot</outputDirectory>
    <artifact>${root}/target/${name}-${version}-bin.tar.bz2</artifact>
  </build>
</dbm>
